"""unique telegram_id

Revision ID: 35ffd6e5e59f
Revises: fb3dfc6c7a9c
Create Date: 2022-11-30 02:17:42.475648

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35ffd6e5e59f'
down_revision = 'fb3dfc6c7a9c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'users', ['telegram_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    # ### end Alembic commands ###
