"""from first/second to full name

Revision ID: fb3dfc6c7a9c
Revises: 2a8e1aa25a57
Create Date: 2022-11-30 02:06:20.008337

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb3dfc6c7a9c'
down_revision = '2a8e1aa25a57'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('fullname', sa.VARCHAR(length=255), nullable=False))
    op.drop_column('users', 'first_name')
    op.drop_column('users', 'second_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('second_name', sa.VARCHAR(length=512), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('first_name', sa.VARCHAR(length=512), autoincrement=False, nullable=False))
    op.drop_column('users', 'fullname')
    # ### end Alembic commands ###
